/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const QuestionIdLazyImport = createFileRoute('/question/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QuestionIdLazyRoute = QuestionIdLazyImport.update({
  path: '/question/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/question/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  QuestionIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/question/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/question/$id": {
      "filePath": "question/$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
