/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const QuestionIndexLazyImport = createFileRoute('/question/')()
const QuestionIdLazyImport = createFileRoute('/question/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QuestionIndexLazyRoute = QuestionIndexLazyImport.update({
  path: '/question/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/question/index.lazy').then((d) => d.Route),
)

const QuestionIdLazyRoute = QuestionIdLazyImport.update({
  path: '/question/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/question/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/question/': {
      id: '/question/'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/question/$id': typeof QuestionIdLazyRoute
  '/question': typeof QuestionIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/question/$id': typeof QuestionIdLazyRoute
  '/question': typeof QuestionIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/question/$id': typeof QuestionIdLazyRoute
  '/question/': typeof QuestionIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/question/$id' | '/question'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/question/$id' | '/question'
  id: '__root__' | '/' | '/question/$id' | '/question/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  QuestionIdLazyRoute: typeof QuestionIdLazyRoute
  QuestionIndexLazyRoute: typeof QuestionIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  QuestionIdLazyRoute: QuestionIdLazyRoute,
  QuestionIndexLazyRoute: QuestionIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/question/$id",
        "/question/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/question/$id": {
      "filePath": "question/$id.lazy.tsx"
    },
    "/question/": {
      "filePath": "question/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
